### ISSUE TITLE
搜圖完全沒有反應

### ISSUE THREAD

**Issue by eric2788** [koishijs/koishi-plugin-image-search#19]
隨便一張圖都沒有反應(連搜索失敗信息都沒有

![image](https://github.com/koishijs/koishi-plugin-image-search/assets/6276840/30aaab6f-b6d1-4945-82e4-c3ae8ef928b0)

![image](https://github.com/koishijs/koishi-plugin-image-search/assets/6276840/138af1e7-28e4-49d1-a0fb-f117089ccf51)

saucenao已配置key

日誌也沒有錯誤輸出

koishi v4.15.0

插件 v4.2.3

可能是我搜索的方式不對?

**Comment by MaikoTan** [comment]
I think it had responded, but the response was not correctly processed by your current adapter.
To verify this, you can use the sandbox in the Koishi Console webui to reproduce your operation and see if the plugin respond you correctly, if so, adapter, otherwise, plugin.

我认为它已响应，但您当前的适配器未正确处理该响应。
为了验证这一点，您可以使用 Koishi Console webui 中的沙箱来重现您的操作，看看插件是否正确响应您，如果是，则为适配器，否则为插件。

**Comment by eric2788** [comment]
好的 我晚上回去試試

**Comment by eric2788** [comment]
试了试，沙盒确实有反应，但是全部都搜索失败(服务器在hk): 
![image](https://github.com/koishijs/koishi-plugin-image-search/assets/6276840/33cefc71-6819-4ffd-8528-c870ec26be98)

我用的是red protocol, 但搜索结果也就只是图片加文字而已，我用的一个pixiv插件都有响应，为啥适配器会未正确处理呢

**Comment by eric2788** [comment]
搜圖沒反應是適配器問題 先關issue
或者之後可以開一個請求適配red的issue🤔
